.circleci/config.yml

copied circleci.yml from demo

---

go.mod
plugin.json
server/apps/app.go
server/apps/app_get.go
server/apps/app_install.go
server/apps/app_list.go
server/apps/expand.go
server/apps/on_user_joined_channel.go
server/apps/placeholder_structs.go
server/apps/proxy.go
server/apps/registry.go
server/apps/subscription.go
server/apps/subscriptions.go
server/command/command.go
server/command/info.go
server/command/main.go
server/constants/constants.go
server/main.go
server/manifest.go
server/plugin/plugin.go

Prep for renaming the repo

---

server/apps/client.go
server/apps/location.go
server/http/helloapp/ping.go

Add AppID to location

---

server/api/binding.go
server/api/call.go
server/api/field.go
server/api/form.go
server/apps/call.go
server/http/helloapp/bindings.go
server/http/helloapp/f_message.go

`Field.Position` has been added, which is a one-based positional argument indicator
`SelectOption.IconData` has been added
Hello app is updated to use these changes
https://github.com/mattermost/mattermost-webapp/pull/6912

Small updates to Binding/Form to support client-side commands

---

server/apps/store/subscriptions_test.go

Add unit tests to Store package
None

Add tests to Store package

---

server/apps/impl/bindings.go
server/apps/impl/proxy.go
server/http/helloapp/bindings.go
server/http/helloapp/f_send_survey.go
server/http/helloapp/f_subscribe.go
server/http/helloapp/helloapp.go
server/http/helloapp/mattermost_client.go

This PR contains updates to support bindings for multiple apps. `AppID` is applied to all bindings and nested bindings. This is subject to change.

Updates for commands

---

docs/interactivity.md

[Rendered docs](https://github.com/mattermost/mattermost-plugin-apps/blob/interactivity-docs/docs/interactivity.md)
This PR is not meant to be merged until we have solidified the payload structures between the proxy plugin and the App servers. Any suggested changes can be discussed in the comments. Once a given change is merged into master, this PR can be updated to reflect that.
https://mattermost.atlassian.net/browse/MM-30440

Interactivity payload docs

---

go.mod
server/api/app.go
server/api/impl/admin/admin.go
server/api/impl/admin/install.go
server/api/impl/admin/synchronize.go
server/api/impl/aws/install_app.go
server/api/impl/store/apps.go
server/api/store.go
server/plugin.go

This PR adds Apps upgrade, downgrade and delete functionality.
One caveat, we need some session token to perform actions. I assumed this token already exists in the admin struct. Will create separate ticket on how to populate the field.
Fixes https://mattermost.atlassian.net/browse/MM-31781

[MM-31781] Apps Upgrade/Downgrade

---

server/api/impl/admin/install.go

Not create an OAuth app if the permissions do not require it
None

Not create an OAuth app if the permissions do not require it

---

server/api/impl/proxy/bindings.go
server/http/restapi/bindings.go

Context was missing MattermostSiteURL and BotAccessToken when asking for bindings.
None

Add missing details for get bindings context

---

.golangci.yml
apps/mmclient/mattermost_client.go
apps/mmclient/mattermost_client_pp.go
server/api/impl/admin/admin.go
server/api/impl/admin/install.go
server/api/impl/appservices/kv.go
server/api/impl/configurator/test_service.go
server/api/impl/proxy/bindings.go
server/api/impl/proxy/bindings_test.go
server/api/impl/proxy/expand.go
server/api/impl/proxy/manifest.go
server/api/impl/store/store.go
server/api/impl/store/subscriptions.go
server/api/upstream.go
server/http/dialog/dialog.go
server/http/restapi/restapitestlib.go
server/http/restapi/subscribe.go
server/utils/httputils/limited_readcloser_test.go

Fix gomimports prefix in `.golangci.yml`
None

Fix goimports prefix

---

server/api/impl/admin/synchronize.go

The working directory of the plugin might not be `plugins/com.mattermost.apps`. Hence, we need to use `GetBundlePath` to get the absolute path.
https://mattermost.atlassian.net/browse/MM-32909

Respect bundle path when reading apps.json

---

server/api/impl/aws/aws_keys.go
server/api/impl/aws/provision_app.go
server/api/impl/aws/s3.go
server/api/impl/aws/service.go

This PR will provision static assets in S3.

Provision static assets

---

server/api/impl/admin/list.go

Helps with debugging
https://mattermost.atlassian.net/browse/MM-33078

[MM-33078] Add app status to /apps list

---

server/api/admin.go
server/api/impl/admin/synchronize.go
server/api/impl/store/apps.go
server/command/main.go
server/command/uninstall.go

This PR adds an `/uninstall` slash command. I've briefly tested it locally, but given some bugs in the code I wasn't able to fully test.
Still, the slash command is a valuable tool for debugging.
https://mattermost.atlassian.net/browse/MM-30046

[MM-30046] Add /uninstall command

---

server/api/impl/store/apps.go

Fix a bad merge introduced in https://github.com/mattermost/mattermost-plugin-apps/commit/3380a5922c4d7d082cc5e7efccf745db3ebfe7fc.
None

Fix bad merge

---

apps/app.go
apps/call.go
server/api/impl/admin/synchronize.go
server/api/impl/proxy/bindings_test.go
server/api/impl/upstream/upawslambda/upstream.go
server/api/impl/upstream/uphttp/upstream.go
server/examples/go/hello/builtin_hello/helloapp.go
server/examples/go/hello/install.go
server/examples/js/aws_hello/helloapp.go

Rename URL to Path in Apps Call
https://mattermost.atlassian.net/browse/MM-31508
- https://github.com/mattermost/mattermost-webapp/pull/7566
- https://github.com/mattermost/mattermost-redux/pull/1370
- https://github.com/mattermost/mattermost-mobile/pull/5186
- https://github.com/mattermost/mattermost-app-zendesk/pull/29
- https://github.com/mattermost/mattermost-app-servicenow/pull/1

[MM-31508] Rename URL to Path in Call

---

apps/context.go

`MattermostSiteURL` was missing from `Context`
https://mattermost.atlassian.net/browse/MM-33399

[MM-33399] Add MattermostSiteURL to Context for slash command

---

assets/apps.json
server/api/impl/admin/provision.go
server/api/impl/admin/synchronization_test.go
server/api/impl/admin/synchronize.go
server/api/impl/store/apps.go

This PR simplifies app sync
Fixes https://mattermost.atlassian.net/browse/MM-33177

[MM-33177] Simplify app sync

---

apps/call.go
server/examples/go/hello/builtin_hello/helloapp.go
server/examples/go/hello/http_hello/functions.go
server/examples/go/hello/install.go
server/examples/go/hello/send_survey.go
server/http/restapi/call.go

Fixes https://mattermost.atlassian.net/browse/MM-31981

Change call type submit and call response ok to not be empty strings

---

server/api/config.go
server/api/impl/configurator/configurator.go
server/api/impl/configurator/test_service.go
server/api/impl/store/subscriptions_test.go
server/api/mock_api/mock_config.go
server/main.go
server/plugin.go

Using pointer has bitten us a couple of times. Given that there is usually no need for pointer, this PR coverts the structs to embed the struct directly instead of using a pointer.
https://mattermost.atlassian.net/browse/MM-33614

Embed directly instead of using pointers

---

docs/01-anatomy-hello.md
server/examples/go/helloworld/hello.go

@mickmister do you mind updating /docs/02-example-post-menu.md and /docs/03-example-interactivity.md with the most recent changes?

Updated helloworld to work with call type changes

---

aws/provision_app.go
aws/provision_data.go
aws/provision_data_test.go

This PR adds manifest key to the provision data

Add manifest key to provisionData

---

Makefile

Use correct flags for go command
https://mattermost.atlassian.net/browse/MM-34462

[MM-34462] Fix /apps info command

---

server/examples/go/hello/send_survey.go

Picking a user should be required for the survey
https://mattermost.atlassian.net/browse/MM-34234

[MM-34234] Require user in http hello survey

---

server/mocks/mock_appservices/mock_appservices.go
server/mocks/mock_proxy/mock_proxy.go

updated mocks

---

server/command/main.go
server/command/service.go

To improve the developers UX this PR adds slash command autocomplete for `/apps`.
I'm 0/5 on all the wording. Fell free to leave suggestions.
In the future a build-in app should we used for the `/apps` command.
https://mattermost.atlassian.net/browse/MM-34522

[MM-34522] Add autocomplete suggestions

---

server/mocks/mock_proxy/mock_proxy.go

fixed mocks

---

docs/01-anatomy-hello.md
docs/06-using-3rdparty-api.md
server/examples/go/hello-oauth2/bindings.json
server/examples/go/helloworld/bindings.json
server/proxy/bindings.go
server/proxy/bindings_test.go

Respect slash command root label instead of using the app ID.
https://mattermost.atlassian.net/browse/MM-34491

[MM-34491] Don't overwrite root command label

---

server/mocks/mock_proxy/mock_proxy.go

Followup on https://github.com/mattermost/mattermost-plugin-apps/pull/119
None

Generate mocks

---

server/http/gateway/oauth2.go
server/http/gateway/static.go
server/http/gateway/webhook.go
server/proxy/install.go
server/proxy/proxy.go

This PR implements a couple of suggestions from https://github.com/mattermost/mattermost-plugin-apps/pull/114. The most eminent is the usage of `crypto/subtle` to compare the secret.
Follow up on https://github.com/mattermost/mattermost-plugin-apps/pull/114

Webhook follow up

---

aws/provision_app.go
aws/provision_data.go

This PR fixes appsctl file close bug
Fixes https://mattermost.atlassian.net/browse/MM-34237

[MM-34237] Fix appsctl asset bug

---

aws/client.go
aws/lambda.go

This PR fixes double marshalling bug
Fixes https://mattermost.atlassian.net/browse/MM-34799

Fix double marshalling

---

server/http/gateway/static.go

This PR adds headers to the static assets
Fixes https://mattermost.atlassian.net/browse/MM-34648

Add headers for static assets

---

plugin.json
server/manifest.go

Version bump 0.3.0

---

server/http/dialog/install.go

https://mattermost.atlassian.net/browse/MM-34997
The setting is not relevant yet (well, neither is creating the OAuth2 app yet, but...)

MM_34997: disabled user consent option in app install dialog

---

examples/go/hello-oauth2/hello.go

Store oauth refreshed token
None

Store refreshed token

---

server/proxy/list.go

Add an `Experimental` label to all installed and listed apps.
Please leave feedback on the wording.
https://mattermost.atlassian.net/browse/MM-34993

[MM-34993] Add Experimental label to all apps

---

assets/manifests.json

Add Zendesk 0.2.0 to manifest list
https://mattermost.atlassian.net/browse/MM-34982

[MM-34982] Add Zendesk 0.2.0 to manifest list

---

plugin.json
server/manifest.go

Part of https://github.com/mattermost/mattermost-plugin-apps/issues/176

Bump version to 0.5.0

---

plugin.json
server/manifest.go

- Changed description text so admins understand what it does and don't disable it accidentally
- Added a link to Apps documentation in the header.

Change description text

---

plugin.json
server/manifest.go

It's possible more changes are going into the release today. Just making the PR to speed up the logistics of releasing
Part of https://github.com/mattermost/mattermost-plugin-apps/issues/185

Bump version to 0.6.0

---

server/command/info.go

Based on https://github.com/mattermost/mattermost-plugin-apps/pull/191
https://mattermost.atlassian.net/browse/MM-36056

[MM-36056] Add modes info

---

upstream/upaws/upstream.go

fixed the crash resulting from a bad merge.
PS, not sure how the e2e test passed before, did it?

Fixed MM-36358, bad merge resulting in crash

---

plugin.json
server/manifest.go

Bump version to 0.7.0
Part of https://github.com/mattermost/mattermost-plugin-apps/issues/204

Bump version to 0.7.0

---

apps/field.go

Add constant for markdown fields
https://mattermost.atlassian.net/browse/MM-31052

Add markdown field constant

---

apps/field.go

Update autocomplete position documentation
Depends on:
https://github.com/mattermost/mattermost-webapp/pull/8153

Update AutocompletePosition documentation

---

.circleci/config.yml

This should fix the issues people have been seeing with e2e tests lately.
None

Wait for Mattermost server to start before running e2e tests

---

server/proxy/install.go

This PR fixes two bugs:
- In 73c2f8e1b7b1436ce57e4e717dd7148c55620d3e a check is added that confirms that the bot icon resource returned a 200. Otherwise if e.g. the file is not found the install process fails much later as the body is blindly passed over to the MM server.
- In d3e373c886b122439a4b89b48890f5c34ff4120f fetching the app icon is moved at the start of the install process allowing it to fail early if the icon can't be fetched.
- https://mattermost.atlassian.net/browse/MM-38190
- https://mattermost.atlassian.net/browse/MM-38015

[MM-38190] [MM-38015] Don't try to set the bot icon in install process if request to it failed

---

server/plugin_test.go

Fixed E2E test faailure on master

Fixed E2E test

---

server/builtin/app.go
server/builtin/debug.go
server/builtin/debug_kv_clean.go
server/builtin/debug_kv_create.go

Fixed a typo @hanzei found, and added a `debug kv create` command which is useful to test when you don't have any keys.

Fixed /apps debug kv clean, added create

---

server/builtin/debug_clean.go
server/builtin/debug_kv_clean.go

Fixed `/apps debug clean` call

---

dev/README.md

Update docs for docker development environment

---

go.mod
server/httpin/restapi/e2e_kv_test.go
server/httpin/restapi/e2e_subscribe_test.go
server/httpin/restapi/main_test.go
server/httpin/restapi/restapitestlib.go

Update to go1.17 in `go.mod`
None

Update to go1.17

---

server/store/apps.go
server/store/manifest.go

Fixes the inconsistency when an app or a manifest are listed in the config (SHA) but the corresponding key is missing in the KV store. Now updates the KV store even when SHA has not changed.

Store app and manifest KV even when SHA did not change

---

assets/i18n/active.en.json
assets/i18n/active.es.json
server/builtin/install.go

Fix install command wording: url -> http

---

server/appservices/oauth2.go
server/appservices/service.go
server/httpin/restapi/app_oauth2_store.go
server/mocks/mock_appservices/mock_appservices.go
server/proxy/expand.go

Fixes https://github.com/mattermost/mattermost-app-servicenow/issues/43

Fix bindings refresh and OAuth2 user

---

plugin.json

Part of https://github.com/mattermost/mattermost-plugin-apps/issues/319

Release v1.0.1

---

server/incoming/request.go
server/proxy/call.go
server/proxy/install.go
server/proxy/list.go

See https://github.com/mattermost/mattermost-plugin-apps/pull/325#discussion_r862727381

#325 feedback: moved WithTimeout to incoming.Request methods

---

dev/docker-compose.yml

Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/333

Docker dev environment: Update server version to 6.6

---

server/proxy/list.go

GetInstalledApps was ignoring the ping parameter and always executing the ping; on top of it, it was leaking a go `chan`.
Maybe related to https://mattermost.atlassian.net/browse/MM-44388

Fixed a bad typo/oversight in proxy.GetInstalledApps

---

.golangci.yml
server/plugin.go
server/store/session.go
test/restapitest/kv_test.go
test/restapitest/oauth2_test.go
test/restapitest/subscribe_test.go

Would have caught https://github.com/mattermost/mattermost-plugin-apps/pull/343.
No actual code changes, only sty/lint meta-comments, and tests.

Style/lint: added unparam to lint

---

apps/subscription.go

https://mattermost.atlassian.net/browse/MM-43659

[MM-43659] Add missing json tag for Subscription.Call

---

server/proxy/list.go

https://mattermost.atlassian.net/browse/MM-43375

[MM-43375] Remove Experimental label from apps in Marketplace

---

test/restapitest/notify.go
test/restapitest/notify_user_left_team.go

Skipping the test for now as it's flaky
https://mattermost.atlassian.net/browse/MM-47962

[MM-47962] Skip TestRESTAPI/notify/user_left_team

---

test/restapitest/oauth2.go

Skip flaky test
https://mattermost.atlassian.net/browse/MM-48448

Skip TestSingleServer/OAuth2/User_and_bot_calls_can_expand_OAuth2App

---

test/restapitest/bindings.go

Skip flaky test
https://mattermost.atlassian.net/browse/MM-48405

Skip TestRESTAPI/bindings/multiple_apps_have_commands

---

test/restapitest/notify_bot_left_team.go

The flaky test is probably related to https://mattermost.atlassian.net/browse/MM-47962
https://mattermost.atlassian.net/browse/MM-48497

Skip TestRESTAPI/notify/bot_left_team

---

server/appservices/subscriptions.go
test/restapitest/subscribe.go

I was learning about the test app, fixes #361

Change message when not subscribe to notification (#361)

---

server/httpin/admin.go

Just a couple comment fixes to address @mickmister's feedback.
Please approve so I can merge, no QA required.

nits/comments: PR feedback for #336

---

server/builtin/settings.go

Follow up on https://github.com/mattermost/mattermost-plugin-apps/pull/372
https://mattermost.atlassian.net/browse/MM-47950

Refresh bindings after setting are saved

---

assets/manifests.json

Update the version of the ServiceNow app to v0.3.4
https://mattermost.atlassian.net/browse/MM-48062

Update ServiceNow to v0.3.4

---

server/proxy/invoke_bindings.go

This PR fixes a regression introduced in https://github.com/mattermost/mattermost-plugin-apps/pull/336.
I don't think it's reasonable to add a test here as it's only about the logging.
https://mattermost.atlassian.net/browse/MM-48916

[MM-48916] Don't try to fet bindings from disabled apps

---

server/proxy/list.go

I've also rewritten the code a bit to make it a bit more readable.
https://mattermost.atlassian.net/browse/MM-49437

[MM-49437] Don't try to ping builtin apps

---

apps/manifest.go
server/proxy/invoke_call.go
test/restapitest/call.go
test/restapitest/main_test.go

See https://mattermost.atlassian.net/browse/MM-49877
https://mattermost.atlassian.net/browse/MM-49877

[MM-49877] Validate call requests paths

---

server/proxy/invoke_call.go
test/restapitest/call.go

See https://mattermost.atlassian.net/browse/MM-49877 and https://mattermost.atlassian.net/browse/MM-49875
https://mattermost.atlassian.net/browse/MM-49875
https://mattermost.atlassian.net/browse/MM-49877

[MM-49875] [MM-49877] Validate default calls

---

server/httpin/service.go

This PR adds the HTTP method, the URL and the user agent to the HTTP request logger.
The logger now logs the message before handling the request. Take makes debugging easier as the flow is more natural.
https://mattermost.atlassian.net/browse/MM-50268

[MM-50268] Add additional fields to HTTP logger

---

.github/workflows/cd.yaml

fix(ci): Remove erroneous dependency

---

.github/workflows/cd.yaml

Downstream https://github.com/mattermost/actions-workflows/pull/23
https://mattermost.atlassian.net/browse/MM-51566

[MM-51566] Fix asset name in plugin release

---

upstream/upaws/provision_data.go

This should make it easier to dev to figure out why the bundle is wrongly built.
https://community.mattermost.com/core/pl/c6nsturm5386dr97z8ypfp96ia

Improve AWS bundle validation errors

---

.github/workflows/ci.yaml

Missed a job in https://github.com/mattermost/mattermost-plugin-apps/pull/492
None

Disable cypress tests for real
