server/apps/expand.go
There's a typo where we're unconditionally returning `nil` in `expander.produce`, when we should be returning the expanded struct.
=> Return expanded struct in `expander.produce` instead of `nil`

server/api/call.go, server/api/call_test.go, server/api/field.go, server/api/form.go, server/api/impl/admin/install.go, server/examples/go/hello/bindings.go, server/examples/go/hello/builtin_hello/helloapp.go, server/examples/go/hello/helloapp.go, server/examples/go/hello/http_hello/functions.go, server/examples/go/hello/http_hello/helloapp.go, server/examples/go/hello/send_survey.go, server/http/restapi/call.go
Each call related to a form uses the same URL:
- fetching form `{type: 'form'}`
- dynamic lookup `{type: 'lookup'}`
- selected significant value `{type: 'form'}`
- submitted form `{type: ''}`
A modal will be opened on the frontend on any call if:
- `call.type` == `submit` (actually empty string at the moment)
- and `callResponse.type` == `form`
Fixes https://mattermost.atlassian.net/browse/MM-30814
Fixes https://mattermost.atlassian.net/browse/MM-30813
https://github.com/mattermost/mattermost-webapp/pull/7166
https://github.com/mattermost/mattermost-redux/pull/1322
=> Updates for dynamic modals

server/api/impl/admin/list.go
Fix markdown formatting for `/apps list` with more then one app installed
None
=> Fix markdown formatting for /apps list with more then one app installed

server/plugin.go
The error came from the embedded struct (StoredConfig) not being init on server restart.
This was due to the server not calling "OnConfigurationChange" after activate. On Enable it behaves like that, (first activate, then onconfigurationchange), but not on server restart.
None
=> Fix panic that happens on server restart

server/api/constants.go, server/http/restapi/marketplace.go, server/http/restapi/marketplace_test.go, server/http/restapi/restapi.go
This PR adds an `/marketplace` endpoint to the plugin. It's used by the webapp to fetch the list of installed and available apps. The latter is a hard coded list for now as discussed in the Apps meeting.
I've added Zendesk as a POW. It only works if the App runs locally, given that it's not yet in AWS.
https://mattermost.atlassian.net/browse/MM-32476
https://mattermost.atlassian.net/browse/MM-32535
https://mattermost.atlassian.net/browse/MM-32539
=> [MM-32476] Apps in the Marketplace

apps/app.go, server/api/impl/aws/provision_app.go
AWS only allows letters, number, underscores and hyphens as function names.
Given that the app id and version are used to generate the function name, we need to limit the characters used in them to only the ones stated above. A version is likely contains a dots, hence I think it's fine to sanitized it before generating the function name.
I've also added an `IsValid` method to `AppID` and `AppVersion` to state that. They should get called in the provision process, but the seemed out of scope for this PR.
https://mattermost.atlassian.net/browse/MM-32862
=> [MM-32862] Sanitized app version and id for function name

server/api/mock_api/mock_appservices.go, server/api/mock_api/mock_proxy.go, server/http/restapi/restapitestlib.go
Reduced the executable size by removing `server/http/restapi/restapitestlib.go` from the default build, tagged it as `e2e`.
vs
=> Reduced the linked image size

server/api/config.go, server/api/impl/store/apps.go
`gob` can't deal with a `map[apps.AppID]interface{}` as it's an unknown type to it. We either need to use a `[]inferface{}` or `map[string]interface{}`. I went with the latter as there are some code areas  that make use of the `map` and I wanted to keep the diff simple. Open for other suggestions.
https://mattermost.atlassian.net/browse/MM-32910
=> [MM-32910] Fix app store

server/api/impl/aws/service.go
Per https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html s3 only allows lower-case characters as bucket names.
https://mattermost.atlassian.net/browse/MM-32902
=> [MM-32902] Fix default s3 bucket name

server/api/impl/store/apps.go
The store did modify the passed `App` and hence caused a panic upstream.
While this PR fixes the bug, I would _love_ for us to stop using pointer even if it's not needed like passing an app to the store.
https://mattermost.atlassian.net/browse/MM-33081
=> [MM-33081] Don't modify app passed to store

server/api/impl/admin/synchronize.go
If a listed files doesn't have a manifest in S3, it should get dropped from the list. The rest of the code base doesn't know how to handle an app without a manifest and panics.
https://mattermost.atlassian.net/browse/MM-33093
=> [MM-33093] Improve handling when manifest is not found on S3

README.md, assets/apps.json, cmd/appsctl/completion.go, cmd/appsctl/log.go, cmd/appsctl/main.go, cmd/appsctl/provision.go, go.mod, go.sum, server/api/aws.go, server/api/impl/aws/provision_app.go, server/api/impl/aws/s3.go, server/api/impl/aws/service.go, server/command/install.go, server/command/main.go
This PR introduces `appsctl` as a tool to manage and provision apps.
The important command is `appsctl provision app` which takes an apps bundle as input and provisions it to AWS. For development purposes there is an `--update` flag that updates the function. In production, we won't be using that, but instead release a new version.
I've added some documentation to the readme.
https://mattermost.atlassian.net/browse/MM-32702
=> [MM-32702] Introduce appsctl

server/api/aws.go, server/api/impl/aws/lambda.go, server/api/impl/upstream/upawslambda/upstream.go
Because the Apps expect HTTP-like requests we have to adopt the payload that is used to invoke the lambda function. The format is documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html). I didn't fill out all fields given that we only need a handful.
There is some double JSON Unmarshaling in the code that I couldn't prevent. Maybe we need to optimize that later.
Given that there is no per path mapping to function right now, all calls go to the first defined function. Hence, the PR kind of drops support for more then one function.
I've tested the PR with the Zendesk app and can confirm that it works.
https://mattermost.atlassian.net/browse/MM-33083
=> [MM-33083] Use HTTP request like payload to invoke lambda

server/api/constants.go, server/api/impl/admin/install.go
When the app gets installed, send a websocket event to the user that installed the app.
There is no need to send the websocket event to all the users, since their experience will not be affected if they have to navigate to another channel to see the effects of the install (since they are not installing the app, they don't know when the app gets installed).
https://mattermost.atlassian.net/browse/MM-33129
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5194
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7599
=> Add refresh websocket event on app install

apps/call.go
To make sure type is properly defined, we force to send the empty string. This way we can do things like `resp.type === OK` instead of considering no type is OK.
None
=> Do not omit type in JSON

apps/context.go, server/api/constants.go, server/http/restapi/bindings.go
Add user agent to call context to allow discriminating between contexts (specially for bindings, but also may be interesting for other calls).
None
Redux: https://github.com/mattermost/mattermost-redux/pull/1379
Mobile: https://github.com/mattermost/mattermost-mobile/pull/5193
=> Add user agent to call context

README.md, plugin.json, server/api/config.go, server/api/impl/aws/service.go, server/api/impl/configurator/configurator.go, server/manifest.go, server/plugin.go
In production, these credentials will be provided by the cloud team and configured via env variables.
https://mattermost.atlassian.net/browse/MM-33377
=> [MM-33377] Move AWS invoke credentials to env variables

server/command/service.go
`Enable OAuth 2.0 Service Provider` is required the run the plugin successfully. I thought erroring  when a slash command is run was the most loudest way I could think of to make admin aware that the setting is needed. 
https://mattermost.atlassian.net/browse/MM-33128
=> [MM-33128] Require Enable OAuth 2.0 Service Provider to run commands

server/api/impl/upstream/upawslambda/upstream.go
The upstream apps expects the call to as JSON. This bug got unnoticed in testing, because JS doesn't differentiate between a JSON like payload and actual JSON.
https://mattermost.atlassian.net/browse/MM-33468
=> [MM-33468] Properly marshal call into JSON body for lambda requests

.circleci/config.yml, .gitignore, Makefile, server/http/restapi/restapitestlib.go
To ensure the go E2E tests are validated on every change, this PR adds them to circleCI. While most of the pipeline is straight forward, one noticeable things is that it does clone `mattermost-server` to ensure the server find the translation files and start.
The PR is based on https://github.com/mattermost/mattermost-plugin-apps/pull/84. The specific changes are in https://github.com/mattermost/mattermost-plugin-apps/commit/419e4b5b5773c37e62fe9f9afb28a1f765dd4d4c.
https://mattermost.atlassian.net/browse/MM-33340
=> [MM-33340] Add e2e tests to CI

server/proxy/bindings_test.go
There is a reordering occurring in the line below, that relies on the display name. This PR adds the display name to the tests to make the order deterministic.
https://github.com/mattermost/mattermost-plugin-apps/blob/e818ca3a03559a961aa4aca056fb5bb196bd7bab/server/proxy/bindings.go#L36-L37
https://github.com/mattermost/mattermost-plugin-apps/blob/e818ca3a03559a961aa4aca056fb5bb196bd7bab/server/store/apps.go#L121
=> Fix flaky bindings test

server/command/debug.go
Add Manifest used to give weird errors like "there is no command with trigger /apps". Now it shows the correct errors.
https://mattermost.atlassian.net/browse/MM-34074
=> Fix debug add manifest command errors

apps/mmclient/mattermost_client_pp.go, aws/lambda.go, aws/provision_data.go, server/examples/go/hello/builtin_hello/helloapp.go, server/http/restapi/restapitestlib.go, server/proxy/bindings_test.go, server/store/manifest.go, server/utils/httputils/limited_readcloser_test.go, server/utils/httputils/utils.go
`io/ioutil` has been deprecated in go 1.16 (https://golang.org/doc/go1.16#ioutil). This PR drops all references to `io/ioutil`.
None
=> Remove io/ioutil

apps/app.go, apps/app_test.go, apps/manifest.go, server/command/debug.go
Given that we use app IDs in the store where key length is limited we should put a stricter limit on the length. Also, 3 characters is now the minimum limit.
https://mattermost.atlassian.net/browse/MM-33020
=> [MM-33020] Make app ID validation more strict

.circleci/config.yml
Ensure mocks are up to date via CI
Broken CI example: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-apps/879/workflows/c9228359-3c62-46f2-a6c1-3780b9022a45/jobs/3003
Successful run: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-apps/881/workflows/513f4678-27db-488d-a3e9-c83f951d569d/jobs/3010
https://mattermost.atlassian.net/browse/MM-34581
=> [MM-34581] Add check that mocks are up to date to CI

apps/call.go, server/proxy/oauth2.go
Remove the Call type (it is not used anymore) and put the right order on the overwrites (we were overwriting the original with the default, and not the other way around).
None
=> Minor fixes regarding OAuth

plugin.json, server/command/info.go, server/command/service.go, server/manifest.go
As discussed offline the term `Cloud Apps` should not longer be used and `Apps` is the sole term.
https://community-daily.mattermost.com/core/pl/3qzqjrye33gofez1kdoustqmzy
=> Drop term "Cloud Apps"

apps/context.go, server/proxy/install.go
This PR changes some things about the bot user when it is created:
- The bot is created regardless if `act_as_bot` was requested
- The bot user's access token is only created if `act_as_bot` was requested
- The bot user's roles are updated to be able to create/read posts in any channel, only created if `act_as_bot` was requested
I'm mainly making this PR to show that we can solve the post permission issue without making the bot a sysadmin. It made sense to implement both tickets in this PR since I was touching post permissions and app permissions already.
Fixes https://mattermost.atlassian.net/browse/MM-34577
Fixes https://mattermost.atlassian.net/browse/MM-34195
=> Manage permissions on bot creation

apps/mmclient/mattermost_client_pp.go, server/http/restapi/get_ids.go, server/http/restapi/restapi.go, server/utils/utils.go
Add API for clients to check the bots and oauth apps ids
https://mattermost.atlassian.net/browse/MM-33158
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7850
=> Add API for clients to check the bots and oauth apps ids

server/proxy/proxy.go
Because we can't trust the client to not sent forged data, `ExpandedContext` needs to be cleared.
https://mattermost.atlassian.net/browse/MM-35034
=> [MM-35034] Clear ExpandedContext before passing it to the App

apps/field.go
The `ReadOnly` field is already supported by the webapp and mobile app. This PR adds the missing `ReadOnly` field on the backend, as well as adding some constants for field types.
https://github.com/mattermost/mattermost-plugin-autolink/pull/159
=> Introduce ReadOnly property for form fields

server/http/dialog/install.go, server/http/gateway/oauth2.go, server/http/gateway/static.go, server/http/restapi/call.go, server/logger/logger.go, server/proxy/bindings.go
https://github.com/mattermost/mattermost-plugin-apps/commit/781dd61f2efa2bf48c5b206cfab226ca48a05d7a adds a `Debug` log message for any call originated from a client. I thought about also logging calls from the apps plugin, but it might be to spammy and the code to do that didn't turn out nice.
https://github.com/mattermost/mattermost-plugin-apps/commit/e6e5a13cb78d172a436a5dfc7d30629687214198 adds logging to certain interesting errors that previously only propagated to the client. I've made use of `github.com/mattermost/mattermost-plugin-api/experimental/bot/logger` by adding a small wrapper around it to make the API fit. Only the cases that are interesting for debugging and not spammy get logged. 
Fixes https://mattermost.atlassian.net/browse/MM-35089
Fixes …
=> [MM-35089] Improve error and call logging

apps/manifest.go
When the user completes oauth2, the call from the proxy plugin should send the expanded user access_token so the 3rd party app can immediately make calls.
N/A
=> include the expanded oauth2 user on oauth2complete

.circleci/config.yml
Please see https://github.com/mattermost/mattermost-server/pull/17559 for the details.
TL;DR: `jhillyerd/inbucket` is not longer available and `mattermost/inbucket` is used as a workaround.
None
=> update inbucket to use mattermost/inbucket:release-1.2.0

e2e/cypress/integration/bindings/channel_header_spec.ts, server/command/install.go, server/command/main.go
Instead of using the named argument `app-id` the app ID is passed as passed as a positional argument. This is consistent with the `/uninstall` command and shorter to use.
https://mattermost.atlassian.net/browse/MM-35184
=> [MM-35184] Pass app ID as positional argument to install command

cmd/appsctl/provision.go, e2e/cypress/integration/bindings/channel_header_spec.ts, server/command/install.go, server/command/service.go, server/mocks/mock_proxy/mock_proxy.go, server/plugin.go, server/proxy/bindings_test.go, server/proxy/install.go, server/proxy/list.go, server/proxy/proxy_test.go, server/proxy/service.go, server/store/manifest.go, server/store/service.go, server/store/service_test.go, server/store/subscriptions_test.go, upstream/upaws/provision_app.go
Instead of install an AWS app via a public readable manifest, there is now a slash command for that. The other commands have been reorganized accordingly:
- `/apps install marketplace com.mattermost.servicenow` is used in Cloud to install from the Marketplace
- `/apps install http http://localhost:3000/manifest --app-secret abc` is used in on-prem to install from an HTTP server
- `/apps install aws com.mattermost.servicenow 0.1.0` is used in on-prem to install an App that was previously deployed to cloud
The PR is based on https://github.com/mattermost/mattermost-plugin-apps/pull/193 to minimize merge conflicts.
None
=> Allow installation from Apps running in AWS directly

apps/form.go
`SubmitOnCancel` is currently not being used by the client, and we haven't designed how that fits within the call requests, so I've removed it from the data model.
`CancelButton` is not used, as we always show the cancel button in the apps modal.
Updates will need to be done in the typescript types when this is merged.
Fixes https://mattermost.atlassian.net/browse/MM-30588
=> Remove CancelButton and SubmitOnCancel form properties

examples/go/hello-webhooks/bindings.json
This PR adds the label field for the hello-webhooks slash command.  Without the label, the `/hello-webhooks` slash command does not appear.
n/a
=> Add label for hello-webhooks command bindings

plugin.json, server/manifest.go
This PR changes the homepage url to point to https://mattermost.com/marketplace/app-framework
This is to match with the changes made in https://github.com/mattermost/mattermost-marketplace/pull/189#issuecomment-843396639
=> Change homepage url to point to docs

server/command/list.go
Instead of combining type and status they are now split into two columns making it easier to understand why an app is shown in the list. The PR also includes some small formatting changes.
https://mattermost.atlassian.net/browse/MM-36226
=> [MM-36226] List type and status separately

apps/binding.go, examples/go/hello-oauth2/bindings.json, examples/go/hello-oauth2/configure_form.json, examples/go/hello-oauth2/connect_form.json, examples/go/hello-oauth2/send_form.json, examples/go/hello-webhooks/bindings.json, examples/go/hello-webhooks/info_form.json, examples/go/hello-webhooks/send_form.json, examples/go/hello-world/bindings.json, examples/go/hello-world/send_form.json, examples/js/hello-world/app.js, server/config/config.go, server/httpin/gateway/static.go, server/proxy/bindings.go, server/proxy/bindings_test.go, server/proxy/expand.go, server/proxy/install.go, server/proxy/proxy.go, server/utils/path.go, server/utils/path_test.go
With this PR apps can define `Icon` for both bindings and forms using a relative path.
Please note that no validation of the asset is done due to performance concerns. Invalid icon with show as invalid in the UI. Only malformed path containing e.g. `/../` are logged and ignored.
Tested with hello-world app.
https://mattermost.atlassian.net/browse/MM-30595
=> [MM-30595] Add support for relative icon path to bindings and forms

server/command/service.go, server/plugin.go
In order for the slash command autocomplete to update the command service needs to re-register the slash command.
I'm not entirely happy with the `Plugin` taking care of deciding which services need to `Reconfigure`. Rather the services register them self at the config store for a `Reconfigure`. But the change seems extends the scope of this PR.
https://mattermost.atlassian.net/browse/MM-36302
=> [MM-36302] Update autocomplete when configuration changes

examples/go/hello-webhooks/hello.go
This PR fetches the path from the correct value in the call request. 
Before:
After PR fix:
n/a
=> get the path value from the request, not the request values

Makefile, apps/app_test.go, apps/manifest.go, apps/manifest_test.go, utils/url.go, utils/url_test.go
Every apps needs to have a valid `HomepageURL`. This is now checked and verified. HTTP apps also need an `HTTPRootURL`.
The PR also fixes two build issue:
- The minimum go version needs to be 1.6
- All `go test` command should run against all packages, not only the ones in `./server`
https://mattermost.atlassian.net/browse/MM-36659
=> [MM-36659] Check for valid HomepageURL

server/proxy/install.go
If the bot user exists and is enabled, the bot account creation process messed up because there is no "full" bot struct after these checks. The bot struct instance was missing the user ID and username, so the `App` struct was missing these values. This was causing issues with the bot info never existing on the `App` struct after installation.
=> Fix issue with creating bot with existing user account

server/command/install.go
When a use tries installing an app with an invalid manifest data, the following error is presented.
This PR wraps the error with a more informative error.
https://mattermost.atlassian.net/browse/MM-37339
=> [MM-3384] wrap manifest json data read error with better description

.circleci/config.yml
Using es7 for pipeline because we no longer support es 5 & 6
https://mattermost.atlassian.net/browse/MM-36445
https://github.com/mattermost/enterprise/pull/1020
=> [MM-36445] Changing elastic search docker version

examples/js/hello-world/app.js
I'm not sure how this was passing on CI on the previous PRs. There was a breaking change between 0.7 and 0.8 that requires Apps to have a `homepage_url`, and the example App was not updated at that time.
=> Add homepage_url to example app to fix CI

e2e/cypress/integration/bindings/channel_header_spec.ts
With recent changes to the webapp, the fully qualified `locations` are fixed for each binding. This has made it so the `id` of the buttons rendered have changed. For a channel header binding with `location` `send-button`, the new `location` is now `/channel_header/send-button`. ~~This PR updates the e2e test to use this new `id`.~~
Edit: Updating the selector to use a new id doesn't work because the CI for individual PRs in this repo doesn't use `mattermost-webapp@master`. The selector in the e2e test is now using the channel header button's `img` `src` attribute to find the element to click.
I've made a [ticket](https://mattermost.atlassian.net/browse/MM-38022) to make sure these id's are namespaced to specific Apps. The current state goes against the HTML spec of enforcing unique id's. …
=> Change selector for e2e test

server/command/list.go
Add comment explaining why `/apps list` is public. This ensure that information that will be added in the futures is carefully checked.
https://mattermost.atlassian.net/browse/MM-37242
=> [MM-37242] Add comment explaining why /apps list is public

server/command/service.go, server/httpin/service.go
The plugin has two main entry points for external request: commands and HTTP requests. A panic in either the command or HTTP handler does shut down the whole plugin. While the plugin health check helps with mitigating the impact, a malicious attacker could continue to crash the plugin until the health check doesn't kick in any longer.
This PR fixes the attack vector by introducing a recovery handler for both command and HTTP requests. Debug information are logged. When the server is running in developer mode it also outputs the debug information in the command response and the HTTP response respectively. That should help developers with debugging without having to switch context.
https://mattermost.atlassian.net/browse/MM-38155
=> [MM-38155] Add recover handler for commands and HTTP requests

server/command/service.go, server/httpin/dialog/install.go, server/httpin/restapi/app.go, server/mmclient/client.go, server/mmclient/http.go, server/mmclient/rpc.go, server/proxy/expand.go
Before this PR apps could expand call to access resources they would not have access otherwise. This PR prevents that by using a permission specific client to expand the calls.
For apps that have the `PermissionActAsAdmin` permission the RPC client is used. If `PermissionActAsUser` is granted, an HTTP client with the users session is used. For `PermissionActAsBot` an HTTP client with the bot session is used.
I've opted for this approach because the apps plugin doesn't need to re-implement the permission checks and just relies on the server to do the right checks.
I tried adding an (go) e2e test for this, but that turned out to be more complicated that I thought. If I get it to work, I will add it later.
https://mattermost.atlassian.net/browse/MM-33770
=> [MM-33770] Use permssion specific client to expands calls

Makefile, build/custom.mk, server/builtin/app.go, server/builtin/info.go, server/config/config.go, server/config/config_test.go, server/config/service.go, server/main.go, server/plugin.go, server/plugin_test.go, server/store/apps.go, server/store/manifest.go
The build hashes were no longer displayed in `/apps info`. 2 causes were identified and fixed.
- package path seems to be different when building as a test and deploy, the latter does not work with `.../server`. Moved the build variables to `.../server/config` which is a FQ, accurate package name and it works in both cases
- https://stackoverflow.com/questions/44148449/how-to-check-whether-golang-binary-is-compiled-with-ldflags-s-w/44168916 - `custom.mk` was adding a separate `-ldflags`, overriding the prior values. Fixed by changing `LDFLAGS` instead of `GO_BUILD_FLAGS`
https://mattermost.atlassian.net/browse/MM-39776
=> MM-39776 moved Build variables to config

apps/appclient/mattermost_client.go, apps/context.go, apps/expand.go, apps/permissions.go, examples/go/hello-webhooks/hello.go, examples/go/hello-webhooks/manifest.json, server/builtin/app.go, server/builtin/debug_bindings.go, server/builtin/debug_clean.go, server/builtin/install_consent.go, server/httpin/restapi/call_test.go, server/proxy/enable.go, server/proxy/expand.go, server/proxy/incoming.go, server/proxy/install.go, server/proxy/uninstall.go
As discussed offline, the `AdminAccessToken` has no clear use case and caused confusion.  This  PR removes it alongside the  `PermissionActAsAdmin`.
This PR targets https://github.com/mattermost/mattermost-plugin-apps/pull/278 to avoid merge conflicts. It should be merged after https://github.com/mattermost/mattermost-plugin-apps/pull/278.
https://mattermost.atlassian.net/browse/MM-39827
- Removed `AdminAccessToken` from `Expand`
- Removed `AdminAccessToken` from `Call.Context`
- Removed `PermissionActAsAdmin` permission
The following apps need to get updated:
=> [MM-39827] Remove AdminAccessToken & PermissionActAsAdmin

server/config/config.go, server/httpin/restapi/restapitestlib.go, server/plugin_test.go
When we create a `Client4` struct for local HTTP requests, we construct the URL manually using the `ListenAddress`, but we don't take into account the server's configured subpath on the site URL. This PR uses the `SiteURL` to calculate the subpath for the constructed URL.
Fixes https://mattermost.atlassian.net/browse/MM-40195
=> Fix subpath for local requests

examples/go/hello-oauth2/hello.go, server/proxy/install.go
Fixed ensureBot replication(?) issue by waiting for the bot record to be available before attempting to `UpdateProfileImage` on the user.
Fixes https://github.com/mattermost/mattermost-app-servicenow/issues/41
=> Fixed bot icon - not found (ServiceNow 41)

Makefile
The cloud servers complain about a missing symbol:
`error relocating plugins/com.mattermost.apps/server/dist/plugin-linux-amd64: __fprintf_chk: symbol not found`
By static linking the binary we not longer rely on a DL to be there.
None?
=> Disable CGO for all builds

.golangci.yml, apps/subscription.go, server/appservices/subscriptions.go, server/mocks/mock_proxy/mock_proxy.go, server/plugin.go, server/proxy/notify.go, server/proxy/notify_test.go, server/proxy/service.go, server/store/subscriptions.go, server/store/subscriptions_test.go, test/app/subscriptions.go
Disabled MessageHasBeenPosted and the related subscription subjects until we figure out performance issues. This disables both `post_created` and `bot_mentioned` notifications.
https://mattermost.atlassian.net/browse/MM-44388
=> disabled MessageHasBeenPosted processing

server/builtin/bindings.go, server/config/config.go, server/config/config_test.go, server/proxy/list.go
- `/apps debug` command is now only visible in dev mode
- @DHaussermann reported seeing HTTP enabled on a production host, so added debugging to see why the regex matches falsely
- Added a small optimization to GetInstalledApps - don't even make a channel if there are no apps installed
None
=> /apps debug is now dev mode only, other feedback from DH

apps/appclient/mattermost_client.go, cmd/appsctl/mattermost.go, test/app/subscriptions.go
- appclient no longer requires a userID to work
- `DM[Post]` errors out if the creator's user ID is not known, with a `empty sender user_id, perhaps Call does not expand acting_user` message. Note that the Bot user id is always expanded.
- Fixed the test apps' subscription parameters
@DHaussermann I did not review every expand in the test app, but it does not use `DM` nor `DMPost` so should be OK.
Embedded does not appear to work, will debug it separately, perhaps @mickmister can help?
=> fixed the test app

cmd/appsctl/aws.go, cmd/appsctl/main.go, upstream/upaws/client.go, upstream/upaws/client_lambda.go, upstream/upaws/provision_app.go, upstream/upaws/provision_data.go
`appsctl aws deploy` now supports:
-  `.jar` file extensions, in addition to .zip. (.jar is essentially a .zip with a special metadata directory).
- `--env='k1=v1,k2=v2'` option for passing environment variables to the deployed Lambda functions
https://mattermost.atlassian.net/browse/MM-43962
https://mattermost.atlassian.net/browse/MM-43961
=> MM-43962: Added support for .jar files in appsctl aws

.circleci/config.yml, test/e2e/cypress/support/index.ts
This PR fixes the issue where the e2e test would get stuck on the webapp's landing page to open the desktop app.
As a follow up to https://github.com/mattermost/mattermost-plugin-apps/pull/362#issuecomment-1279257314, I tried using the test app rather than the hello app for the e2e tests, but the test app currently doesn't test things like sending bot DMs, so it's currently not available to be a drop-in replacement.
=> Fix e2e tests for webapp master branch

test/app/main.go
That should make it easier for people to find the secret and serves as a reminder to set it.
Fixes #392
=> Include JWT secret in test app startup message

cmd/appsctl/aws.go, cmd/appsctl/main.go, utils/logger.go
This PR adds two improvments for `appscl`.
1. The log output is now colored.
2. Add a `--version` flag. 
3. Instead of printing a fantal error two times, the error is only printed once, making it more readable.
```bash
$ go run . aws clean
Error: no AWS access key was provided. Please set MM_APPS_DEPLOY_AWS_ACCESS_KEY
Usage:
appsctl aws clean [flags]
Flags:
-h, --help   help for clean
Global Flags:
-q, --quiet     quiet (errors only) output
-v, --verbose   verbose (debug) output
2022-11-21T16:54:35.336+0100	FATAL	appsctl/main.go:38	command failed	{"error": "no AWS access key was provided. Please set MM_APPS_DEPLOY_AWS_ACCESS_KEY"}
main.main
/home/bschumacher/src/mattermost/plugins/apps/cmd/appsctl/main.go:38
runtime.main
/usr/local/go/src/runtime/proc.go:250
exit status 1
```
```bash
$ go …
```
=> [MM-48533] Enable color logs

test/app/channel_header.go, test/app/command.go, test/app/const.go, test/app/main.go, test/app/num_bindings.go, test/app/post_menu.go
This PR serves as a tool to test the functionality of the client-side functionality of the App framework. It adds a command `/test num_bindings (location) (number)` that allows you to set the number of bindings like so:
- `/test num_bindings post_menu 2` - two items in the post menu
- `/test num_bindings channel_header 0` - no items in the channel header / Apps bar
- `/test num_bindings channel_header -1` - normal set of test bindings
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/401
=> Test app - Add num_bindings command to set number of bindings in different locations

server/httpin/service.go, server/incoming/request.go, server/plugin_test.go, utils/plugin_logger.go
12b7e8878c4bd61c21c7f87f945b9c2ac77b649a add callers to the both the file logger. and the channel logger
```
{"timestamp":"2022-12-07 14:09:06.564 +01:00","level":"debug","msg":"Handled HTTP request","caller":"app/plugin_api.go:970","plugin_id":"com.mattermost.apps","request_id":"t51n6ercg3y78bqshyuj1d559r","path":"/api/v1/bindings","plugin_caller":"server/httpin/service.go:164","from_user_id":"78r48k3iy3b8bxmzfqzsbdnhra"}
```
11f0b7e5acfd317c475d522f43d4bd04c80df01f ensures that `source_plugin_id` is only added if it's not empty, which is most of the time. This make the log messages easier to read.
479a20b22f1df7dee74caa6eb7af0f79c0fd9f70 changes a log message to make it more readable.
Follow up on https://github.com/mattermost/mattermost-plugin-apps/pull/394
=> Include caller in logs

server/httpin/admin.go, server/proxy/list.go
E.g. the ServiceNow App _can_ be deployed as a plugin, but isn't in Cloud. `api/v1/marketplace?include_plugins=false` should return it.
This PR relaxes the checks around `includePluginApps` to only filter the apps out that are deployed as plugins or can only be deployed as plugins.
https://mattermost.atlassian.net/browse/MM-49164
=> [MM-49164] Include apps that can be deployed as plugins but aren't in Marketplace response

server/proxy/install.go, server/proxy/invoke_static.go, server/proxy/list.go
Propagate any errors from `/ping` to the end user to make debugging easier.
Part of https://mattermost.atlassian.net/browse/MM-49992
=> [MM-49992] Propagate errors from /ping

server/config/service.go, server/plugin.go, server/plugin_test.go
If the server config is invalid, e.g. because `SITE_URL` is not set, the logger returned from `config.MakeService` is `nil`. In that case, the plugin logger should be used instead.
https://mattermost.atlassian.net/browse/MM-50054
=> [MM-50054] Fix panic on server with invalid configuration

.github/workflows/cd.yaml, build/custom.mk
After some name changing, MM_RUDDER_WRITE_KEY has become MM_RUDDER_PLUGINS_PROD.
Fix custom.mk so we get the right data.
Additionally, the variable mapping in the build workflow has been removed.
no
=> fix rudder key secret name and remove wrong env mapping

.github/workflows/cd.yaml, .github/workflows/ci.yaml
Using the prod Rudderstack telemetry key in CI can skew our telemetry numbers. The production builds of the plugin produced by the `cd.yml` should still contain the prod key. This PR We makes it so we use the development key instead for the `ci.yml` workflow.
Fixes https://github.com/mattermost/mattermost-plugin-apps/issues/469
=> Remove reference to prod rudder key in ci workflow, keep in cd workflow

test/restapitest/admin.go, test/restapitest/helper.go, test/restapitest/kv.go, test/restapitest/main_test.go, test/restapitest/timer.go, test/restapitest/uninstall.go
Add restapi tests for https://github.com/mattermost/mattermost-plugin-apps/pull/375
https://mattermost.atlassian.net/browse/MM-48342
=> Add restapi tests for stateful timers

server/proxy/notify.go, server/store/subscriptions.go
If a newly created channel is a DM, the `ChannelHasBeenCreated` hook gets called with an empty `TeamID`. This leads to an error down the stack. Now, `ChannelHasBeenCreated` gets ignored for DMs.
I did try adding a test, but the only symptom of the bug is a log message (https://github.com/mattermost/mattermost-plugin-apps/blob/22741daa176f919160193831d3bd2f113aa369c8/server/proxy/notify.go#L225-L229) which is hard to test for.
https://mattermost.atlassian.net/browse/MM-51931
=> [MM-51931] Don't send channel_created event for DMs

server/proxy/expand.go
Having `channel: summary` in the expand section of an app (using app framework) make it unusable in the context of a group channel with the error message
```
failed to expand context: failed post-expand consistency check: expanded channel's team ID  is different from user agent context 1ntjrqrqdjy8mffhoc44g1e9zr
```
This is because, like Direct channels, the Group channel type has no TeamID so the consistency check fail and the expand fail, preventing from firing the application call.
This pull request fixes that behavior by ignoring Group Channels on the TeamID consistency check
Fixes mattermost/mattermost#27271 and JIRA [MM-58505](https://mattermost.atlassian.net/browse/MM-58505)
=> [MM-58505] Fix group channel expand

.github/workflows/ci.yaml
The Cypress tests are broken, and there is no one to fix them. Let's disable them.
None
=> Disable broken Cypress tests

README.md
Updated `README.md` to emphasize that this repository is deprecated, and link to the now legacy documentation for anyone who still needs it.
Fixes: https://github.com/mattermost/mattermost-plugin-apps/issues/494
=> docs: Add deprecation notice to README.md
